### ISSUE TITLE
Install still not functioning: emply bundle generated

### ISSUE THREAD

**Issue by RJPvT** [kid1194/frappe-list-unassign-from#2]
Hi @kid1194 still not seeing the button in the menu. the errors are gone but i still get a :

Building frappe_list_unassign_from assets...

EMPTY_BUNDLE : Generated an empty bundle
✔ Built js/unassign_from.js
✨ Done in 0.002s
Done in 34.17s.
Compiling Python files...

**Comment by kid1194** [comment]
@RJPvT Thank you for reporting this..

I have updated the plugin so please give it another try and let me know if you still face the same problem..

Best regards..

**Comment by RJPvT** [comment]
Almost there.
install is working and bundle is created by v1.0.6 but following error 👍 
![afbeelding](https://github.com/kid1194/frappe-list-unassign-from/assets/48353029/82507598-a74b-4a7f-bad3-dc77c2710e95)

i think 

frappe.views.ListView = frappe.views.ListView.extend({

should be

frappe.views.ListView = class ListView extends frappe.views.ListView({

**Comment by kid1194** [comment]
@RJPvT I apologize for my mistake and thanks for pointing it out..

I have fixed it. Please inform me if you face any problem..

Best regards..

**Comment by RJPvT** [comment]
No applogies needed, i think i also made an error :

i'm getting a Uncaught (in promise) TypeError: this._super is not a function error in the JS side and no visible ListView

**Comment by RJPvT** [comment]
perhaps :
        actions_menu_items = super.get_actions_menu_items();

**Comment by kid1194** [comment]
@RJPvT I missed that so thanks for reminding me. I have fixed the plugin. 

Best regards..

**Comment by RJPvT** [comment]
All is visible now :-)

in regards to pushing the button 

ImportError: cannot import name 'Locate' from 'frappe.query_builder.functions' (apps/frappe/frappe/query_builder/functions.py)

{
	"type": "GET",
	"args": {
		"doctype": "Task",
		"txt": "",
		"query": "frappe_list_unassign_from.api.search_link",
		"filters": "{\"docname\":[\"TASK-2019-00216\",\"TASK-2019-00215\"]}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link"
}
Response JSON
{
	"exception": "ImportError: cannot import name 'Locate' from 'frappe.query_builder.functions' (apps/frappe/frappe/query_builder/functions.py)"
}

  File "apps/frappe_list_unassign_from/frappe_list_unassign_from/api/__init__.py", line 7, in 
    from .unassign_from import *
  File "apps/frappe_list_unassign_from/frappe_list_unassign_from/api/unassign_from.py", line 8, in 
    from frappe.query_builder.functions import Locate
ImportError: cannot import name 'Locate' from 'frappe.query_builder.functions' (apps/frappe/frappe/query_builder/functions.py)

will look at that one in (my) morning :_)

thanks so far Ahmed!

**Comment by kid1194** [comment]
@RJPvT The python code was written for v14 but now I used a simple code that should work on both v13 & v14..

Again, thanks a lot bro..

Best regards..

**Comment by RJPvT** [comment]
I'm getting 

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 41, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 100, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 88, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1474, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 270, in validate_and_sanitize_search_inputs
    kwargs["page_len"] = cint(kwargs["page_len"])
KeyError: 'page_len'

but this does not look like your doing. ?

**Comment by kid1194** [comment]
@RJPvT This is a frappe bug, but I solved it by not requesting the code that causes this error 😁

**Comment by RJPvT** [comment]
Thought so, i'll also make a PR on frappe for this ;) 

Thanks for all the help!

Any integrations you're still looking for ? I made a few in a private repo you're welcome to look at (v13) 😜

**Comment by kid1194** [comment]
@RJPvT I have a lot of things I want to integrate with frappe/Erpnext but currently I have limited time for that..
